### PR TITLE
Feature/buttons

### PR DESCRIPTION
**Pull request by olehpanadii**
button elements not included hover and focus for any elements

### CODE REVIEW

**Review by KaterynaSch — COMMENTED** [review]
- You probably meant blue - # 5FE4F9 instead of the gradient on the border button (added by you in tailwind.config.ts);
- Button-component and import Button name conflict from "@ mui/material/Button";

**Comment by olehpanadii** [comment]
I did revert of one problematic commit, so currently i can't see any conflicts on my local devise. Could you please review this moment from the side of main branch. 
Also about gradient colours of borders in 1px how we discuss before are not really visible so do we need to follow that information or not? Especially  this button on the side bar has colour which doesn't looks like with gradient. 
Thank you in advance

**Comment by KaterynaSch** [comment]
Yes, now everything is fine, there are no conflicts. As for the gradient on the border and the hovers - we will take out this question on the meet. Thank you for the quick response!

**Comment by olehpanadii** [comment]
In the last update you can find some changes in tailwind.config file - there are some new shadows for hover and focus status. And updated list with new buttons. As we spoke with our PM we will make custom buttons with absolute position img on them,  directly in the component. And there are some buttons like "submit" i need some one who could review text position for discover parameters in px. Thank you  🙌🏻

**Pull request merged**
